### ISSUE TITLE
Problema con Autentificación 

### ISSUE THREAD

**Issue by geopablus** [csaybar/EarthEngineMasterGIS#1]
Hola César,

Soy Juan Pablo Orán y estoy haciendo el curso de MASTERGIS.

Primero gracias por tus clases, voy lento pero aprendiendo y con deseos de seguir haciéndolo.

Aunque ya estoy en el jupyter notebook "02_EDGEE" tengo una duda arrastrada desde la anterior. No soy capaz de autentificarme como dijiste en versión "experto". He intentado de la manera que indicas en el vídeo y nada, y luego vi que hay cambios en el "01_EDGEE" y tampoco soy capaz (adjunto captura).

Espero puedas darme algo de luz.

Muchas gracias de antemano.

![image](https://user-images.githubusercontent.com/36490905/90428909-fc571a00-e0c4-11ea-8bab-5143705ddac9.png)

**Comment by csaybar** [comment]
Hola @geopablus gracias por abrir este issue.

Aqui el problema es que la API de GEE va cambiando mucho, yo las clases las grave antes de que existiera `ee.Authenticate`, te recomiendo ahora correr así:

```py
import ee
ee.Authenticate()
ee.Initialize()
```
La API de GEE siempre esta en beta y las cosas que funcionan para una versión pueden no hacerla para la siguiente, creo que sería bastante bueno siempre tener esto presente. Cualquier otra duda te agradecería puedas hacerlo por aquí!
Saludos!

https://github.com/google/earthengine-api
![image](https://user-images.githubusercontent.com/16768318/90429987-466fd980-e08c-11ea-922e-9c32f9e58f10.png)

**Comment by geopablus** [comment]
Muchas gracias César por responder tan rápido. Así lo haré, esperemos que vuelvan a habilitar una forma mas automática de acceder aunque no es una tortura tampoco, jeje.

Un saludo
